import type { Metadata } from "next";
import { Fira_Sans_Extra_Condensed, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });
const firsSansExtraCondensed = Fira_Sans_Extra_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${firsSansExtraCondensed.className} bg-slate-950`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
